# Generated by Django 4.1 on 2022-09-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ccategory',
            new_name='category',
        ),
    ]
